jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          workflow_name: 'Crypto Pump-Dump Screener'
          retain_days: 3
          keep_minimum_runs: 5

      - name: Delete old artifacts
        uses: actions/delete-artifacts@v3
        with:
          days-ago: 3   # delete artifacts older than 3 days
