name: Cleanup old workflow runs

on:
  schedule:
    - cron: '0 0 * * *'  # daily at midnight UTC

concurrency:
  group: cleanup-runs
  cancel-in-progress: true

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          workflow_name: 'Crypto Pump-Dump Screener'  # optional, only clean this workflow
          retain_days: 3      # keep last 3 days
          keep_minimum_runs: 5
