name: Cleanup old workflow runs

on:
  schedule:
    - cron: '0 0 * * *'  # run daily

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 1      # keep last 3 days
          keep_minimum_runs: 5
